using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace CTEditor.GameDefinition.Editor
{
    /// <summary>
    /// TODOS los textos que ve el autor para los CAMPOS y las OPCIONES de las fichas, en español.
    ///
    /// El código está en inglés (nombres de campos y enums), pero la interfaz no: el Inspector, las
    /// ventanas y las cabeceras de Excel leen de aquí. Así, el día de mañana, cambiar de idioma es
    /// cambiar este diccionario (o cargar otro) sin tocar el código de las fichas.
    ///
    ///   Field("residualDamagePercent")  → "Daño por turno (% PS máx.)"
    ///   Enum("Physical")                → "Físico"
    ///   CsvHeader("residualDamagePercent") → "daño_por_turno"
    /// </summary>
    public static class Etiquetas
    {
        // (campo) -> (etiqueta en el Inspector, cabecera corta para Excel)
        private static readonly Dictionary<string, (string label, string csv)> Fields = new Dictionary<string, (string, string)>
        {
            // Comunes
            ["id"] = ("Id (único, sin espacios)", "id"),
            ["displayName"] = ("Nombre visible", "nombre"),
            ["description"] = ("Descripción", "descripcion"),
            ["color"] = ("Color", "color"),
            ["icon"] = ("Icono", "icono"),

            // Movimientos
            ["type"] = ("Tipo", "tipo"),
            ["category"] = ("Categoría", "categoria"),
            ["power"] = ("Potencia", "potencia"),
            ["neverMisses"] = ("Nunca falla", "nunca_falla"),
            ["accuracy"] = ("Precisión (%)", "precision"),
            ["maxPp"] = ("PP máximos", "pp"),
            ["priority"] = ("Prioridad", "prioridad"),
            ["target"] = ("Objetivo", "objetivo"),
            ["secondaryEffects"] = ("Efectos", "efectos"),
            ["minHits"] = ("Golpes mínimos", "golpes_min"),
            ["maxHits"] = ("Golpes máximos", "golpes_max"),
            ["critStage"] = ("Etapa de crítico", "critico"),
            ["twoTurn"] = ("Dos turnos", "dos_turnos"),
            ["makesContact"] = ("Hace contacto", "contacto"),
            ["fixedDamage"] = ("Daño especial", "daño_especial"),
            ["fixedDamageAmount"] = ("PS exactos (fijo) · % (devolver)", "daño_fijo"),
            ["sideConditionId"] = ("Efecto de lado", "efecto_lado"),
            ["turns"] = ("Turnos", "turnos"),
            ["typeId"] = ("Tipo nuevo", "tipo_nuevo"),
            ["physicalDamageMultiplier"] = ("Daño físico recibido ×", "mult_fisico"),
            ["specialDamageMultiplier"] = ("Daño especial recibido ×", "mult_especial"),
            ["blocksStatDrops"] = ("Impide bajadas de estadísticas", "sin_bajadas"),
            ["blocksStatus"] = ("Impide estados", "sin_estados"),
            ["speedMultiplier"] = ("Velocidad ×", "mult_velocidad"),
            ["respectsTypeImmunity"] = ("Respeta la inmunidad de tipo", "respeta_inmunidad"),
            ["powerModifiers"] = ("Modificadores de potencia", "potencia_mod"),
            ["powerFormula"] = ("Fórmula de potencia", "formula_potencia"),
            ["attackStat"] = ("Estadística de ataque", "stat_ataque"),
            ["defenseStat"] = ("Estadística de defensa", "stat_defensa"),
            ["attackStatFromTarget"] = ("Ataca con la estadística del rival", "ataca_con_rival"),
            ["tags"] = ("Etiquetas", "etiquetas"),
            ["animationSeconds"] = ("Duración de la animación (s)", "animacion"),

            // Efecto de movimiento
            ["chancePercent"] = ("Probabilidad (%)", "probabilidad"),
            ["kind"] = ("Qué hace", "efecto"),
            ["statusId"] = ("Estado", "estado"),
            ["amountPercent"] = ("Cantidad (%)", "cantidad"),
            ["statStatId"] = ("Estadística", "estadistica"),
            ["statStages"] = ("Etapas (+ sube, − baja)", "etapas"),
            ["weatherId"] = ("Clima", "clima"),
            ["weatherTurns"] = ("Turnos del clima (0 = los de su ficha)", "turnos_clima"),
            ["sharesPreviousRoll"] = ("Mismo dado que el efecto anterior", "mismo_dado"),
            ["conditions"] = ("Condiciones (todas deben cumplirse)", "condiciones"),
            ["multiplier"] = ("Multiplicador", "multiplicador"),

            // Estados
            ["isVolatile"] = ("Es volátil (se suma al principal)", "volatil"),
            ["residualDamagePercent"] = ("Daño por turno (% PS máx.)", "daño_por_turno"),
            ["progressiveResidual"] = ("El daño crece cada turno", "daño_creciente"),
            ["residualHeals"] = ("Cura en vez de dañar", "cura_por_turno"),
            ["actionPreventionChance"] = ("Probabilidad de no actuar (%)", "prob_no_actuar"),
            ["clearedOnSwitch"] = ("Se cura al retirarse", "se_cura_al_retirarse"),
            ["durationTurns"] = ("Duración en turnos (0 = hasta curarse)", "duracion"),
            ["durationMaxTurns"] = ("Duración máxima (al azar)", "duracion_max"),
            ["recoveryChancePerTurn"] = ("Probabilidad de recuperarse cada turno (%)", "prob_recuperarse"),
            ["selfDamageOnPreventedPercent"] = ("Autodaño al no actuar (% PS máx.)", "autodaño"),
            ["transformsToStatus"] = ("Al terminar se convierte en", "se_convierte_en"),
            ["passiveModifiers"] = ("Cambios de estadísticas mientras dura", "modificadores"),
            ["immuneTypes"] = ("Tipos inmunes", "tipos_inmunes"),
            ["preventsSwitch"] = ("Impide cambiarse y huir", "impide_cambio"),
            ["blocksIncomingMoves"] = ("Bloquea los ataques del rival", "bloquea_ataques"),
            ["survivesLethalHit"] = ("Aguanta con 1 PS", "aguanta"),
            ["residualHealsOpponent"] = ("El daño por turno cura al rival", "cura_al_rival"),
            ["harderWhenRepeated"] = ("Más difícil si se repite", "mas_dificil_si_repite"),
            ["statId"] = ("Estadística", "estadistica"),

            // Habilidades
            ["statusImmunities"] = ("Inmune a los estados", "inmune_estados"),
            ["typeImmunities"] = ("Inmune a los tipos", "inmune_tipos"),
            ["absorbImmuneHealPercent"] = ("Cura al absorber (% PS máx.)", "cura_al_absorber"),
            ["contactReactionStatus"] = ("Estado al recibir contacto", "estado_por_contacto"),
            ["contactReactionChance"] = ("Probabilidad por contacto (%)", "prob_contacto"),
            ["onEntryStatId"] = ("Al entrar: estadística", "entrada_stat"),
            ["onEntryStages"] = ("Al entrar: etapas", "entrada_etapas"),
            ["onEntryTargetsSelf"] = ("Al entrar: sobre sí mismo", "entrada_propio"),
            ["statusStatBoostStatId"] = ("Con estado: estadística que sube", "con_estado_stat"),
            ["statusStatBoostMultiplier"] = ("Con estado: multiplicador", "con_estado_mult"),
            ["lowHpBoostType"] = ("Poca vida: tipo potenciado", "poca_vida_tipo"),
            ["lowHpThresholdPercent"] = ("Poca vida: umbral (% PS)", "poca_vida_umbral"),
            ["lowHpBoostMultiplier"] = ("Poca vida: multiplicador", "poca_vida_mult"),
            ["incomingTypeMultipliers"] = ("Daño recibido por tipo", "daño_recibido_tipo"),
            ["stabMultiplierOverride"] = ("Multiplicador de mismo tipo (0 = 1,5)", "stab"),
            ["statusMovePriorityBonus"] = ("Prioridad extra en movimientos de estado", "prioridad_estado"),
            ["preventsStatReduction"] = ("Impide que le bajen estadísticas", "impide_bajadas"),
            ["curesStatusOnSwitchOut"] = ("Se cura el estado al retirarse", "cura_al_retirarse"),
            ["healPercentOnSwitchOut"] = ("Cura al retirarse (% PS máx.)", "cura_ps_al_retirarse"),
            ["endOfTurnStatId"] = ("Fin de turno: estadística", "fin_turno_stat"),
            ["endOfTurnStages"] = ("Fin de turno: etapas", "fin_turno_etapas"),
            ["endOfTurnHealPercent"] = ("Fin de turno: cura (% PS máx.)", "fin_turno_cura"),
            ["endOfTurnHealRequiresStatus"] = ("Fin de turno: solo si tiene estado", "fin_turno_con_estado"),
            ["endOfTurnCureStatusChance"] = ("Fin de turno: prob. de curarse el estado (%)", "fin_turno_curar_estado"),
            ["negatesStatusDamage"] = ("Anula el daño de los estados", "anula_daño_estado"),
            ["offensivePowerModifiers"] = ("Potencia al atacar", "potencia_al_atacar"),
            ["defensivePowerModifiers"] = ("Potencia al recibir", "potencia_al_recibir"),

            // Especies
            ["types"] = ("Tipos", "tipos"),
            ["hp"] = ("PS", "ps"),
            ["attack"] = ("Ataque", "ataque"),
            ["defense"] = ("Defensa", "defensa"),
            ["spAttack"] = ("Ataque especial", "atq_esp"),
            ["spDefense"] = ("Defensa especial", "def_esp"),
            ["speed"] = ("Velocidad", "velocidad"),
            ["customStats"] = ("Estadísticas inventadas", "stats_extra"),
            ["value"] = ("Valor", "valor"),
            ["abilityId"] = ("Habilidad", "habilidad"),
            ["growthCurveId"] = ("Curva de experiencia", "curva"),
            ["baseExpYield"] = ("Experiencia que da", "exp_base"),
            ["evYield"] = ("EV que da", "evs"),
            ["amount"] = ("Cantidad", "cantidad"),
            ["learnset"] = ("Movimientos que aprende", "aprende"),
            ["move"] = ("Movimiento", "movimiento"),
            ["level"] = ("Nivel", "nivel"),
            ["evolutions"] = ("Evoluciones", "evoluciona"),
            ["requiredLevel"] = ("Nivel", "nivel"),
            ["method"] = ("Cómo evoluciona", "metodo"),
            ["itemId"] = ("Objeto", "objeto"),
            ["minFriendship"] = ("Amistad mínima (0 = 220)", "amistad_min"),
            ["baseFriendship"] = ("Amistad inicial", "amistad_inicial"),

            // Tipos y tabla
            ["matchups"] = ("Enfrentamientos", "enfrentamientos"),
            ["attacking"] = ("Tipo que ataca", "ataca"),
            ["defending"] = ("Tipo que defiende", "defiende"),

            // Curvas
            ["formula"] = ("Forma de la curva", "forma"),
            ["maxLevel"] = ("Nivel máximo", "nivel_max"),
            ["xpMultiplierPercent"] = ("Velocidad global (% de XP necesaria)", "multiplicador_xp"),
            ["customTable"] = ("Tabla propia (XP total por nivel)", "tabla"),
            ["formulaSegments"] = ("Tramos de fórmula", "tramos"),
            ["fromLevel"] = ("Desde el nivel", "desde_nivel"),
            ["expression"] = ("Fórmula", "formula"),

            // Naturalezas
            ["boostedStatId"] = ("Estadística que sube", "sube"),
            ["hinderedStatId"] = ("Estadística que baja", "baja"),
            ["boostPercent"] = ("Porcentaje", "porcentaje"),

            // Reglas
            ["maxPartySize"] = ("Tamaño máximo del equipo", "equipo_max"),
            ["maxMovesPerMonster"] = ("Movimientos por monstruo", "movimientos_max"),
            ["levelCap"] = ("Nivel máximo", "nivel_max"),
            ["damageFormulaId"] = ("Fórmula de daño", "formula_daño"),
            ["maxIv"] = ("IV máximo", "iv_max"),
            ["maxEvPerStat"] = ("EV máximo por estadística", "ev_max_stat"),
            ["maxEvTotal"] = ("EV máximo total", "ev_max_total"),
            ["usePp"] = ("Los movimientos gastan PP", "usa_pp"),
            ["struggleMoveId"] = ("Movimiento sin PP (Forcejeo)", "forcejeo"),
            ["critDenominators"] = ("Tabla de críticos (1 entre N por etapa)", "tabla_criticos"),
            ["critMultiplier"] = ("Multiplicador del crítico", "multiplicador_critico"),
            ["physicalAttackStat"] = ("Físico: estadística de ataque", "fisico_ataque"),
            ["physicalDefenseStat"] = ("Físico: estadística de defensa", "fisico_defensa"),
            ["specialAttackStat"] = ("Especial: estadística de ataque", "especial_ataque"),
            ["specialDefenseStat"] = ("Especial: estadística de defensa", "especial_defensa"),

            // Reglas de generación
            ["generation"] = ("Generación de referencia (0 = personalizada)", "generacion"),
            ["categoryByType"] = ("Categoría por tipo (1.ª-3.ª gen.)", "categoria_por_tipo"),
            ["specialTypes"] = ("Tipos especiales (con categoría por tipo)", "tipos_especiales"),
            ["singleSpecialStat"] = ("Especial único (1.ª gen.)", "especial_unico"),
            ["abilitiesEnabled"] = ("Hay habilidades", "hay_habilidades"),
            ["heldItemsEnabled"] = ("Se pueden equipar objetos", "hay_objetos_equipados"),
            ["naturesEnabled"] = ("Hay naturalezas", "hay_naturalezas"),
            ["gendersEnabled"] = ("Hay géneros", "hay_generos"),
            ["mechanicIds"] = ("Mecánicas especiales activas", "mecanicas"),
            // Mecánicas especiales
            ["mechanicKind"] = ("Tipo de mecánica", "tipo_mecanica"),
            ["megaMaxPerBattle"] = ("Megas por combate y lado (0 = sin límite)", "megas_por_combate"),
            ["megaRequiredKeyItem"] = ("Objeto clave del jugador (Megapulsera)", "objeto_clave"),
            ["megaRevertOnSwitch"] = ("Vuelve a su forma al retirarse", "revierte_al_cambiar"),

            // Climas
            ["defaultTurns"] = ("Turnos que dura", "turnos"),
            ["typePowerMultipliers"] = ("Potencia por tipo", "potencia_por_tipo"),

            // Objetos
            ["price"] = ("Precio", "precio"),
            ["usableInBattle"] = ("Se usa en combate", "en_combate"),
            ["usableOutsideBattle"] = ("Se usa fuera del combate", "fuera_combate"),
            ["consumable"] = ("Se gasta al usarlo", "se_gasta"),
            ["healHp"] = ("Cura PS (cantidad fija)", "cura_ps"),
            ["healPercent"] = ("Cura PS (% del máximo)", "cura_pct"),
            ["curesAllStatus"] = ("Cura cualquier estado", "cura_todo"),
            ["curesStatusId"] = ("Cura estos estados", "cura_estados"),
            ["revives"] = ("Revive", "revive"),
            ["reviveHpPercent"] = ("Revive con (% PS)", "revive_pct"),
            ["restorePp"] = ("Recupera PP", "recupera_pp"),
            ["restorePpAllMoves"] = ("A todos los movimientos", "pp_todos"),
            ["friendshipChange"] = ("Cambio de amistad", "amistad"),
            ["catchMultiplier"] = ("Multiplicador de captura (0 = no es bola)", "captura"),
            ["battleStatId"] = ("En combate: estadística", "combate_stat"),
            ["battleStages"] = ("En combate: etapas", "combate_etapas"),
            ["heldPowerModifiers"] = ("Equipado: potencia", "equipado_potencia"),
            ["heldEndOfTurnHealPercent"] = ("Equipado: cura por turno (% PS)", "equipado_cura_turno"),
            ["heldTriggerHpPercent"] = ("Equipado: se activa con PS ≤ (%)", "equipado_umbral"),
            ["heldTriggerHealHp"] = ("Equipado: cura al activarse (PS)", "equipado_cura_ps"),
            ["heldTriggerHealPercent"] = ("Equipado: cura al activarse (% PS)", "equipado_cura_pct"),
            ["heldConsumedOnTrigger"] = ("Equipado: se consume al activarse", "equipado_se_consume"),

            // Escena / equipo
            ["members"] = ("Miembros del equipo", "miembros"),
            ["species"] = ("Especie", "especie"),
            ["moves"] = ("Movimientos", "movimientos"),
            ["nature"] = ("Naturaleza", "naturaleza"),
            ["fixedIvs"] = ("IV fijos (−1 = al azar)", "ivs"),
            ["heldItem"] = ("Objeto equipado", "objeto_equipado"),
            ["persistAcrossScenes"] = ("Mantener entre escenas", "persistir"),
            ["geneticsSeed"] = ("Semilla de la genética (0 = al azar)", "semilla"),
            ["startingItems"] = ("Mochila inicial", "mochila"),
            ["quantity"] = ("Cantidad", "cantidad"),

            // Pantalla de combate (BattleScreen) y demo (GameBootstrap)
            ["opponent"] = ("Rival de este combate", "rival"),
            ["partyOverride"] = ("Equipo del jugador (para pruebas)", "equipo_prueba"),
            ["seed"] = ("Semilla del azar", "semilla"),
            ["aiLevel"] = ("Dificultad de la IA", "ia"),
            ["potionItemId"] = ("Objeto del botón Mochila", "objeto_mochila"),
            ["ballItemId"] = ("Bola del botón Capturar", "bola"),
            ["potionCount"] = ("Pociones (si no hay mochila)", "pociones"),
            ["potionHeal"] = ("PS que cura la poción (sin mochila)", "cura_pocion"),
            ["potionCuresStatus"] = ("La poción cura estados (sin mochila)", "pocion_cura_estado"),
            ["ballCount"] = ("Bolas (si no hay mochila)", "bolas"),
            ["catchBonus"] = ("Multiplicador de captura (sin mochila)", "bono_captura"),
            ["playerNameText"] = ("Texto: nombre del jugador", "t_nombre_jugador"),
            ["enemyNameText"] = ("Texto: nombre del rival", "t_nombre_rival"),
            ["playerLevelText"] = ("Texto: nivel del jugador", "t_nivel_jugador"),
            ["enemyLevelText"] = ("Texto: nivel del rival", "t_nivel_rival"),
            ["playerHpBar"] = ("Barra de PS del jugador", "barra_jugador"),
            ["enemyHpBar"] = ("Barra de PS del rival", "barra_rival"),
            ["playerHpText"] = ("Texto: PS del jugador", "t_ps_jugador"),
            ["enemyHpText"] = ("Texto: PS del rival", "t_ps_rival"),
            ["playerDebug"] = ("Depuración: jugador", "debug_jugador"),
            ["enemyDebug"] = ("Depuración: rival", "debug_rival"),
            ["messageText"] = ("Texto del mensaje", "t_mensaje"),
            ["logText"] = ("Texto del registro", "t_registro"),
            ["advanceButton"] = ("Botón para avanzar", "b_avanzar"),
            ["charsPerSecond"] = ("Letras por segundo", "letras_seg"),
            ["autoAdvanceSeconds"] = ("Avance automático (s, 0 = no)", "auto_avance"),
            ["hpDrainSeconds"] = ("Duración de la bajada de PS (s)", "bajada_ps"),
            ["actionPanel"] = ("Panel de acciones", "p_acciones"),
            ["movePanel"] = ("Panel de movimientos", "p_movimientos"),
            ["switchPanel"] = ("Panel de cambio", "p_cambio"),
            ["fightButton"] = ("Botón Luchar", "b_luchar"),
            ["switchButton"] = ("Botón Cambiar", "b_cambiar"),
            ["bagButton"] = ("Botón Mochila", "b_mochila"),
            ["catchButton"] = ("Botón Capturar", "b_capturar"),
            ["fleeButton"] = ("Botón Huir", "b_huir"),
            ["backButton"] = ("Botón Atrás", "b_atras"),
            ["moveButtons"] = ("Botones de movimientos", "b_movimientos"),
            ["switchButtons"] = ("Botones de cambio", "b_cambio"),
            ["playerSpecies"] = ("Especie del jugador", "especie_jugador"),
            ["enemySpecies"] = ("Especie del rival", "especie_rival"),
            ["typeChart"] = ("Tabla de tipos", "tabla_tipos"),
            ["ruleset"] = ("Reglas", "reglas"),
            ["playerLevel"] = ("Nivel del jugador", "nivel_jugador"),
            ["enemyLevel"] = ("Nivel del rival", "nivel_rival"),
            ["secondsPerBeat"] = ("Segundos por mensaje", "seg_mensaje"),
            ["wild"] = ("Es salvaje (se puede capturar)", "salvaje"),
            ["matchupsList"] = ("Enfrentamientos", "enfrentamientos"),

            // Especies y estados: captura
            ["catchRate"] = ("Ratio de captura (1-255)", "ratio_captura"),
            ["hazardId"] = ("Trampa", "trampa"),
            ["maxLayers"] = ("Capas máximas", "capas"),
            ["damagePercentByLayer"] = ("Daño por capa (% PS máx.)", "daño_por_capa"),
            ["damageScalesWithType"] = ("Daño × eficacia del tipo", "tipo_daño"),
            ["statusByLayer"] = ("Estado por capa", "estado_por_capa"),
            ["stages"] = ("Etapas", "etapas"),
            ["immuneIfAbilityBlocksType"] = ("Inmune si su habilidad bloquea el tipo", "inmune_por_habilidad"),
            ["absorbedByTypes"] = ("La retiran los tipos", "la_retiran"),
            ["statusCatchMultiplier"] = ("Facilita la captura (×)", "captura_x"),

            // Reglas de la aventura
            ["fleeAlwaysWorks"] = ("Huir de salvajes funciona siempre", "huir_siempre"),
            ["canFleeTrainerBattles"] = ("Se puede huir de entrenadores", "huir_entrenador"),
            ["canCatchTrainerMonsters"] = ("Se capturan monstruos de entrenadores", "capturar_entrenador"),
            ["catchRateMultiplier"] = ("Facilidad de captura global (×)", "captura_global"),
            ["sendToBoxWhenFull"] = ("Equipo lleno: el capturado va al PC", "al_pc"),
            ["expShareAll"] = ("Repartir Experiencia a todo el equipo", "repartir_exp"),
            ["expShareOthersPercent"] = ("Repartir Exp.: % para los que no lucharon", "repartir_pct"),
            ["learnMovesOnLevelUp"] = ("Aprende movimientos al subir de nivel", "aprende_al_subir"),
            ["evolveAfterBattle"] = ("Evoluciona al terminar el combate", "evoluciona_tras_combate"),
            ["friendshipPerLevelUp"] = ("Amistad al subir de nivel", "amistad_nivel"),
            ["friendshipLostOnFaint"] = ("Amistad perdida al debilitarse", "amistad_debilitado"),
            ["startingMoney"] = ("Dinero inicial", "dinero_inicial"),
            ["moneyLostOnBlackoutPercent"] = ("Dinero perdido al perder (%)", "dinero_perdido"),
            ["healOnBlackout"] = ("Al perder, el equipo se cura", "cura_al_perder"),

            // Entrenadores, equipos prearmados y zonas salvajes
            ["trainerClass"] = ("Clase de entrenador", "clase"),
            ["portrait"] = ("Retrato", "retrato"),
            ["team"] = ("Equipo", "equipo"),
            ["ai"] = ("Nivel de IA", "ia"),
            ["useItems"] = ("Usa objetos", "usa_objetos"),
            ["check"] = ("Qué comprueba", "comprueba"),
            ["useSystemClock"] = ("Hora del reloj del ordenador", "reloj_sistema"),
            ["fixedHour"] = ("Hora fija", "hora_fija"),
            ["startLocationId"] = ("Lugar de inicio", "lugar_inicio"),
            ["text"] = ("Lugar o marca", "texto"),
            ["time"] = ("Momento del día", "momento"),
            ["relation"] = ("Ataque frente a Defensa", "relacion"),
            ["negate"] = ("Al revés (cuando NO pasa)", "al_reves"),
            ["healBelowPercent"] = ("Se cura con PS ≤ (%)", "curar_bajo"),
            ["canSwitch"] = ("Puede cambiar de monstruo", "puede_cambiar"),
            ["baseMoney"] = ("Dinero base (× nivel del último)", "dinero_base"),
            ["introLine"] = ("Frase al empezar", "frase_inicio"),
            ["defeatLine"] = ("Frase al perder", "frase_derrota"),
            ["victoryLine"] = ("Frase al ganar", "frase_victoria"),
            ["nickname"] = ("Mote", "mote"),
            ["money"] = ("Dinero (−1 = el de las reglas)", "dinero"),
            ["items"] = ("Mochila", "mochila"),
            ["entries"] = ("Especies de la zona", "especies"),
            ["minLevel"] = ("Nivel mínimo", "nivel_min"),
            ["weight"] = ("Frecuencia (peso)", "frecuencia"),

            // Partida y laboratorio de pruebas (escena)
            ["startMode"] = ("Cómo empieza la partida", "modo_inicio"),
            ["teamPreset"] = ("Equipo prearmado", "equipo_prearmado"),
            ["starterSpecies"] = ("Monstruo inicial", "inicial"),
            ["starterLevel"] = ("Nivel del inicial", "nivel_inicial"),
            ["playerName"] = ("Nombre del jugador", "nombre_jugador"),
            ["trainers"] = ("Entrenadores para probar", "entrenadores"),
            ["zones"] = ("Zonas salvajes para probar", "zonas"),
            ["battleScreen"] = ("Pantalla de combate", "pantalla_combate"),
            ["labPanel"] = ("Panel del laboratorio", "panel_lab"),
            ["battleRoot"] = ("Interfaz del combate", "interfaz_combate"),
            ["depositButton"] = ("Botón: dejar en el PC", "b_dejar_pc"),
            ["withdrawButton"] = ("Botón: sacar del PC", "b_sacar_pc"),
            ["infoText"] = ("Texto: información", "t_info"),
            ["teamText"] = ("Texto: equipo", "t_equipo"),
            ["wildButton"] = ("Botón: combate salvaje", "b_salvaje"),
            ["trainerButton"] = ("Botón: combate contra entrenador", "b_entrenador"),
            ["prevTrainerButton"] = ("Botón: entrenador anterior", "b_ent_ant"),
            ["nextTrainerButton"] = ("Botón: entrenador siguiente", "b_ent_sig"),
            ["prevZoneButton"] = ("Botón: zona anterior", "b_zona_ant"),
            ["nextZoneButton"] = ("Botón: zona siguiente", "b_zona_sig"),
            ["healButton"] = ("Botón: Centro (curar)", "b_curar"),
            ["resetButton"] = ("Botón: reiniciar partida", "b_reiniciar"),
            ["leadButtons"] = ("Botones: poner primero", "b_primero"),
            ["confirmPanel"] = ("Panel de sí/no", "panel_confirmar"),
            ["yesButton"] = ("Botón: Sí", "b_si"),
            ["noButton"] = ("Botón: No", "b_no"),
            ["bagPanel"] = ("Panel de la mochila", "panel_mochila"),
            ["bagButtons"] = ("Botones de la mochila", "b_mochila"),
            ["moneyText"] = ("Texto: dinero", "t_dinero"),
            ["startOnPlay"] = ("Empezar el combate al pulsar Play", "empezar_en_play"),
            ["opponentMode"] = ("Tipo de rival", "tipo_rival"),
            ["trainer"] = ("Entrenador rival", "entrenador"),
            ["zone"] = ("Zona salvaje", "zona"),
            ["wildSpecies"] = ("Especie salvaje", "especie_salvaje"),
            ["wildLevel"] = ("Nivel del salvaje", "nivel_salvaje"),
            // Pokédex y requisitos
            ["dexNumber"] = ("Número de Pokédex", "numero"),
            ["category"] = ("Categoría (Pokémon ...)", "categoria"),
            ["heightM"] = ("Altura (m)", "altura"),
            ["weightKg"] = ("Peso (kg)", "peso"),
            ["dexColor"] = ("Color", "color"),
            ["dexDescription"] = ("Descripción", "descripcion"),
            ["femalePercent"] = ("% de hembras (-1 = sin género)", "hembras"),
            ["legendary"] = ("Legendario", "legendario"),
            ["requirements"] = ("Requisitos (si no, falla)", "requisitos"),
            ["movesetStyle"] = ("Movimientos automáticos", "movimientos_auto"),
            ["secondAbilityId"] = ("Segunda habilidad", "habilidad_2"),
            ["hiddenAbilityId"] = ("Habilidad oculta", "habilidad_oculta"),
            ["machineMoves"] = ("Movimientos por MT", "mt"),
            ["tutorMoves"] = ("Movimientos de tutor", "tutor"),
            ["eggMoves"] = ("Movimientos huevo", "huevo"),
            ["eggGroups"] = ("Grupos huevo", "grupos_huevo"),
            ["cannotBreed"] = ("No puede criar", "no_cria"),
            ["aiLevel"] = ("Nivel de IA (1-7)", "nivel_ia"),
            ["knowledge"] = ("Qué sabe de ti", "conocimiento"),
            ["heldItems"] = ("Objetos equipados", "objetos_equipados"),
            ["competitiveTraining"] = ("Entrenamiento de competición (IVs 31, EVs, naturaleza)", "entrenamiento"),
            ["custom"] = ("IA personalizada (solo para los entrenadores que la eligen)", "personalizada"),
            ["aiProfileId"] = ("IA personalizada (id)", "ia_personalizada"),
            ["predictPercent"] = ("% de turnos que juega por predicción", "prediccion"),
            ["gender"] = ("Género", "genero"),
            ["requiresOppositeGender"] = ("Solo al género opuesto (Atracción)", "genero_opuesto"),
            // --- 5.ª y 6.ª generación: objetos de competición ---
            ["heldStatMultipliers"] = ("Equipado: estadísticas × (con condiciones)", "equipado_stats"),
            ["heldChoiceLock"] = ("Equipado: bloquea en el primer movimiento (Elección)", "eleccion"),
            ["heldAttackRecoilPercent"] = ("Equipado: % de PS que pierde al atacar (Vidasfera)", "pierde_al_atacar"),
            ["heldSurviveFromFullHp"] = ("Equipado: aguanta con 1 PS desde PS llenos (Banda Focus)", "aguanta_1ps"),
            ["heldContactDamagePercent"] = ("Equipado: % de PS que pierde quien le toca (Casco Dentado)", "daño_contacto"),
            ["heldOnHitStats"] = ("Equipado: cambios de etapa al recibir un golpe", "equipado_al_recibir_golpe"),
            ["heldOnHitConsumed"] = ("Equipado: se gasta al activarse (Seguro Debilidad)", "se_gasta_al_golpe"),
            ["heldAirBalloon"] = ("Equipado: inmune a Tierra hasta que le golpean (Globo Helio)", "globo"),
            ["heldBlocksStatusMoves"] = ("Equipado: no puede usar movimientos de estado (Chaleco Asalto)", "sin_mov_estado"),
            ["heldCritStageBonus"] = ("Equipado: + índice de crítico", "critico_equipado"),
            ["heldAccuracyMultiplier"] = ("Equipado: precisión de sus movimientos ×", "precision_x"),
            ["heldEvasionMultiplier"] = ("Equipado: precisión de quien le ataca ×", "evasion_x"),
            ["heldResistBerryType"] = ("Equipado: baya que resiste este tipo", "baya_resiste"),
            ["heldCuresAnyStatus"] = ("Equipado: cura cualquier estado y se gasta (Ziuela)", "cura_estado_equipado"),
            ["heldSelfStatusEndOfTurn"] = ("Equipado: se pone este estado al final del turno (esferas)", "estado_propio"),
            ["heldFlinchChance"] = ("Equipado: % de hacer retroceder", "retroceso_equipado"),
            ["heldHealOnDamagePercent"] = ("Equipado: % del daño hecho que recupera (Campana Concha)", "recupera_del_daño"),
            ["heldWeatherTurnsBonus"] = ("Equipado: turnos extra del clima (rocas)", "clima_extra"),
            ["heldScreenTurnsBonus"] = ("Equipado: turnos extra de pantallas (Refleluz)", "pantallas_extra"),
            ["heldBlackSludge"] = ("Equipado: Lodo Negro (cura a Veneno, daña al resto)", "lodo_negro"),
            ["heldQuickClawChance"] = ("Equipado: % de actuar el primero (Garra Rápida)", "garra_rapida"),
            ["heldSuperEffectiveBoost"] = ("Equipado: daño de los golpes muy eficaces ×", "muy_eficaz_x"),
            // --- 5.ª y 6.ª generación: habilidades ---
            ["priorityType"] = ("Tipo con prioridad extra (Alas Vendaval)", "tipo_prioridad"),
            ["priorityTypeBonus"] = ("Prioridad extra de ese tipo", "prioridad_tipo"),
            ["contactStatDrop"] = ("Al recibir contacto: estadística que baja al atacante (Baba)", "contacto_baja_stat"),
            ["contactStatDropStages"] = ("Al recibir contacto: etapas que baja", "contacto_baja_etapas"),
            ["stealOnHit"] = ("Roba el objeto al golpear (Prestidigitador)", "roba_objeto"),
            ["spreadsAbilityOnContact"] = ("Contagia la habilidad por contacto (Momia)", "contagia_habilidad"),
            ["convertNormalTo"] = ("Movimientos Normales pasan a este tipo (Piel Feérica)", "normal_a_tipo"),
            ["convertBoost"] = ("Potencia de esos movimientos ×", "normal_a_tipo_x"),
            ["berryBonusHealPercent"] = ("Al comer baya recupera además % de PS (Carrillo)", "baya_extra"),
            // --- 5.ª y 6.ª generación: protecciones y efectos de campo ---
            ["protectOnlyDamaging"] = ("Protege solo de ataques que hacen daño (Escudo Real)", "protege_solo_daño"),
            ["protectContactStat"] = ("Al bloquear contacto: estadística que baja al atacante", "protege_baja_stat"),
            ["protectContactStages"] = ("Al bloquear contacto: etapas que baja", "protege_baja_etapas"),
            ["protectContactDamagePercent"] = ("Al bloquear contacto: % de PS que pierde el atacante", "protege_daño"),
            ["swapsDefenses"] = ("Intercambia Defensa y Def. Esp. (Zona Extraña)", "intercambia_defensas"),
            ["suppressesItems"] = ("Anula los objetos equipados (Zona Mágica)", "anula_objetos"),
            ["group"] = ("Grupo (solo uno activo: campos)", "grupo"),
            ["groundedStatusBlock"] = ("Estados que impide a quien pisa el suelo (* = todos)", "impide_estados"),
            // --- 3.ª y 4.ª generación: habilidades, estados y efectos de lado ---
            ["onEntryWeather"] = ("Al entrar: clima que pone", "clima_al_entrar"),
            ["onEntryWeatherTurns"] = ("Al entrar: turnos del clima (0 = permanente)", "clima_al_entrar_turnos"),
            ["suppressesWeather"] = ("Anula el clima (Aclimatación)", "anula_clima"),
            ["weatherHpChanges"] = ("PS por turno según el clima", "ps_por_clima"),
            ["weatherImmunities"] = ("Inmune al daño de estos climas", "inmune_climas"),
            ["curesStatusInWeather"] = ("Se cura el estado con este clima", "cura_con_clima"),
            ["statusImmuneInWeather"] = ("Inmune a estados con este clima", "sin_estados_con_clima"),
            ["typeByWeather"] = ("Su tipo según el clima (Predicción)", "tipo_por_clima"),
            ["noRecoil"] = ("Sin retroceso (Cabeza Roca)", "sin_retroceso"),
            ["noIndirectDamage"] = ("Solo le dañan los ataques (Muro Mágico)", "solo_daño_directo"),
            ["critImmune"] = ("No recibe críticos", "sin_criticos"),
            ["critStageBonus"] = ("+ índice de crítico", "critico_extra"),
            ["critDamageMultiplier"] = ("Daño de sus críticos ×", "daño_critico"),
            ["preventedStatDrops"] = ("Estadísticas que no le pueden bajar", "no_bajan"),
            ["flinchImmune"] = ("No retrocede", "sin_retroceder"),
            ["onFlinchStat"] = ("Al retroceder sube", "al_retroceder_stat"),
            ["onFlinchStages"] = ("Al retroceder: etapas", "al_retroceder_etapas"),
            ["secondaryChanceMultiplier"] = ("Prob. de sus efectos secundarios ×", "secundarios_mult"),
            ["blocksIncomingSecondaries"] = ("No le afectan los secundarios (Polvo Escudo)", "bloquea_secundarios"),
            ["removesOwnSecondaries"] = ("Sin efectos secundarios propios (Potencia Bruta)", "sin_secundarios"),
            ["flinchChanceOnAttack"] = ("% de hacer retroceder (Hedor)", "hace_retroceder"),
            ["forcedSwitchImmune"] = ("No le obligan a cambiar (Ventosas)", "no_cambio_forzado"),
            ["trapsOpponent"] = ("Atrapa al rival", "atrapa"),
            ["trapOnlyTypes"] = ("Solo atrapa a estos tipos", "atrapa_tipos"),
            ["trapOnlyGrounded"] = ("Solo atrapa a los que pisan el suelo", "atrapa_en_suelo"),
            ["alwaysEscapes"] = ("Siempre escapa (Fuga)", "siempre_escapa"),
            ["sleepAgesTwice"] = ("Despierta el doble de rápido (Madrugar)", "madrugar"),
            ["synchronizeStatus"] = ("Devuelve el estado (Sincronía)", "sincronia"),
            ["contactReactionStatuses"] = ("Estados por contacto (uno al azar)", "estados_por_contacto"),
            ["contactDamagePercent"] = ("Daña al que le toca (% PS)", "daño_por_contacto"),
            ["offensiveContactStatus"] = ("Al golpear con contacto pone", "estado_al_golpear"),
            ["offensiveContactChance"] = ("Prob. al golpear con contacto", "prob_al_golpear"),
            ["aftermathPercent"] = ("Daña al que lo debilita (% PS)", "resquicio"),
            ["disableOnHitChance"] = ("% de anular el golpe recibido", "anula_al_recibir"),
            ["critMaxesAttack"] = ("Un crítico le maximiza el Ataque", "irascible"),
            ["ohkoImmune"] = ("Inmune a KO de un golpe", "sin_ko_directo"),
            ["survivesFromFullHp"] = ("Aguanta con 1 PS si estaba al máximo", "robustez"),
            ["immuneToMoveTags"] = ("Inmune a movimientos con etiqueta", "inmune_etiquetas"),
            ["blocksMoveTagsForAll"] = ("Nadie usa movimientos con etiqueta", "bloquea_etiquetas"),
            ["onlySuperEffectiveHits"] = ("Solo le dañan los muy eficaces", "superguarda"),
            ["onImmuneStat"] = ("Al absorber sube", "al_absorber_stat"),
            ["onImmuneStages"] = ("Al absorber: etapas", "al_absorber_etapas"),
            ["boostsAbsorbedType"] = ("Potencia el tipo absorbido (Absorbe Fuego)", "potencia_absorbido"),
            ["traceOnEntry"] = ("Copia la habilidad rival (Rastro)", "rastro"),
            ["transformOnEntry"] = ("Se transforma al entrar (Impostor)", "impostor"),
            ["downloadOnEntry"] = ("Descarga", "descarga"),
            ["announceOnEntry"] = ("Avisa al entrar (objeto / peligro / movimiento)", "avisa_al_entrar"),
            ["neutralizingGas"] = ("Anula las habilidades (Gas Reactivo)", "gas_reactivo"),
            ["unnerve"] = ("El rival no come bayas (Nerviosismo)", "nerviosismo"),
            ["colorChange"] = ("Cambio Color", "cambio_color"),
            ["protean"] = ("Mutatipo", "mutatipo"),
            ["pressure"] = ("Presión (gasta 1 PP más)", "presion"),
            ["truant"] = ("Ausente (un turno sí, otro no)", "ausente"),
            ["ignoresStages"] = ("Ignora las etapas del rival (Ignorante)", "ignorante"),
            ["stageMultiplier"] = ("Multiplica sus cambios de etapa (Simple)", "etapas_mult"),
            ["invertsStages"] = ("Invierte sus cambios de etapa (Respondón)", "invierte_etapas"),
            ["liquidOoze"] = ("Lodo Líquido", "lodo_liquido"),
            ["normalizeMoves"] = ("Todo Normal (Normalidad)", "normalidad"),
            ["ignoresImmunityFor"] = ("Alcanza a inmunes con estos tipos (Intrépido)", "ignora_inmunidad"),
            ["moldBreaker"] = ("Rompemoldes", "rompemoldes"),
            ["skillLink"] = ("Golpes múltiples al máximo (Encadenado)", "encadenado"),
            ["badDreamsPercent"] = ("Daña al rival dormido (% PS)", "mal_sueño"),
            ["noGuard"] = ("Nada falla (Indefenso)", "indefenso"),
            ["movesLast"] = ("Actúa el último (Rezagado)", "rezagado"),
            ["klutz"] = ("Su objeto no hace nada (Zoquete)", "zoquete"),
            ["berryThresholdPercent"] = ("Come bayas con este % de PS", "umbral_bayas"),
            ["stickyHold"] = ("No le quitan el objeto (Viscosidad)", "viscosidad"),
            ["pickpocket"] = ("Roba al que le toca (Hurto)", "hurto"),
            ["onKoStat"] = ("Al debilitar a un rival sube", "al_debilitar_stat"),
            ["onKoStages"] = ("Al debilitar: etapas", "al_debilitar_etapas"),
            ["onStatDroppedStat"] = ("Si le bajan una stat sube", "si_bajan_stat"),
            ["onStatDroppedStages"] = ("Si le bajan: etapas", "si_bajan_etapas"),
            ["harvestChance"] = ("% de recuperar su baya (Cosecha)", "cosecha"),
            ["moody"] = ("Veleta", "veleta"),
            ["infiltrator"] = ("Atraviesa pantallas y sustitutos (Allanamiento)", "allanamiento"),
            ["magicBounce"] = ("Devuelve los de estado (Espejo Mágico)", "espejo_magico"),
            ["weightMultiplier"] = ("Multiplica su peso", "peso_mult"),
            ["blocksStatusMoves"] = ("No puede usar movimientos de estado (Mofa)", "bloquea_estado"),
            ["blocksRepeatedMove"] = ("No puede repetir movimiento (Tormento)", "bloquea_repetir"),
            ["blocksHealing"] = ("No puede curarse (Anticura)", "bloquea_curar"),
            ["blocksItems"] = ("No puede usar objetos (Embargo)", "bloquea_objetos"),
            ["suppressesAbility"] = ("Anula su habilidad (Bilis)", "anula_habilidad"),
            ["residualRequiresStatus"] = ("El daño por turno necesita este estado", "daño_si_estado"),
            ["faintsWhenEnds"] = ("Se debilita al acabar (Canto Mortal)", "debilita_al_acabar"),
            ["destinyBond"] = ("Mismo Destino", "mismo_destino"),
            ["grudge"] = ("Rabia (deja sin PP)", "rabia"),
            ["reflectsStatusMoves"] = ("Devuelve los de estado (Capa Mágica)", "devuelve_estado"),
            ["stealsBoostMoves"] = ("Roba las mejoras (Robo)", "robo"),
            ["boostedType"] = ("Tipo potenciado (Carga)", "tipo_potenciado"),
            ["boostMultiplier"] = ("Multiplicador del tipo potenciado", "tipo_potenciado_mult"),
            ["boostConsumed"] = ("El refuerzo se gasta", "refuerzo_se_gasta"),
            ["extraTypeImmunities"] = ("Inmune a estos tipos mientras dura (Levitón)", "inmune_tipos_extra"),
            ["suppressedType"] = ("Pierde este tipo mientras dura (Respiro)", "pierde_tipo"),
            ["identified"] = ("Identificado (Profecía)", "identificado"),
            ["hittableByTypes"] = ("Le alcanzan estos tipos aunque fuera inmune", "alcanzable_por"),
            ["sureHit"] = ("Su próximo movimiento no falla (Fijar Blanco)", "no_falla"),
            ["imprisons"] = ("Cerca (el rival no usa sus movimientos)", "cerca"),
            ["grounded"] = ("En el suelo (Arraigo, Gravedad)", "en_suelo"),
            ["reversesTurnOrder"] = ("El más lento va primero (Espacio Raro)", "espacio_raro"),
            ["accuracyMultiplier"] = ("Precisión ×", "precision_mult"),
            ["groundsTargets"] = ("Todos en el suelo (Gravedad)", "gravedad"),
            ["blocksCrits"] = ("Sin críticos contra este lado (Conjuro)", "bloquea_criticos"),
            ["typeDamageMultipliers"] = ("Daño de un tipo × (Chapoteolodo)", "daño_tipo_mult"),
            ["brain"] = ("Cómo elige el movimiento", "cerebro"),
            ["mistakePercent"] = ("% de fallos al azar", "fallos"),
            ["itemUsePercent"] = ("% que se acuerda de sus objetos", "uso_objetos"),
            ["heal"] = ("Cómo se cura", "curacion"),
            ["moveset"] = ("Movimientos automáticos", "movimientos_auto"),
            ["synergies"] = ("Busca sinergias", "sinergias"),
            ["useMachineMoves"] = ("Usa movimientos de MT", "usa_mt"),
            ["useTutorMoves"] = ("Usa movimientos de tutor", "usa_tutor"),
            ["useEggMoves"] = ("Usa movimientos huevo", "usa_huevo"),
            ["autoHeldItems"] = ("Pone objetos equipados", "objetos_equipados"),
            ["defaultBag"] = ("Mochila por defecto", "mochila"),
            // Interfaz: menús (fichas y escena)
            ["title"] = ("Título", "titulo"),
            ["options"] = ("Opciones", "opciones"),
            ["columns"] = ("Columnas", "columnas"),
            ["wrap"] = ("Volver al principio al pasar del final", "vuelta"),
            ["rememberCursor"] = ("Recordar dónde estaba el cursor", "recordar_cursor"),
            ["cancelCloses"] = ("Cancelar cierra el menú", "cancelar_cierra"),
            ["cancelOptionId"] = ("Opción que elige Cancelar", "opcion_cancelar"),
            ["anchor"] = ("Sitio en la pantalla", "sitio"),
            ["label"] = ("Texto", "texto"),
            ["action"] = ("Qué hace", "accion"),
            ["requiredFlag"] = ("Solo con la marca", "marca_requerida"),
            ["hiddenByFlag"] = ("Oculta con la marca", "marca_oculta"),
            ["help"] = ("Ayuda", "ayuda"),
            ["optionId"] = ("Id de la opción", "id_opcion"),
            ["screenId"] = ("Id del menú (el que sustituye)", "id_menu"),
            ["navigation"] = ("Cómo se mueve el cursor", "navegacion"),
            ["onCancel"] = ("Al pulsar Cancelar", "al_cancelar"),
            ["cursor"] = ("Cursor (imagen o texto)", "cursor"),
            ["cursorOffset"] = ("Posición del cursor", "pos_cursor"),
            ["titleText"] = ("Texto del título", "t_titulo"),
            ["helpText"] = ("Texto de ayuda", "t_ayuda"),
            ["itemTemplate"] = ("Opción de plantilla (lista)", "plantilla"),
            ["visibleRows"] = ("Filas que se ven", "filas"),
            ["moreAbove"] = ("Indicador «hay más arriba»", "mas_arriba"),
            ["moreBelow"] = ("Indicador «hay más abajo»", "mas_abajo"),
            ["background"] = ("Imagen de fondo", "fondo"),
            ["normalSprite"] = ("Imagen normal", "img_normal"),
            ["selectedSprite"] = ("Imagen al elegirla", "img_elegida"),
            ["disabledSprite"] = ("Imagen desactivada", "img_desactivada"),
            ["tintBackground"] = ("Teñir el fondo", "tenir_fondo"),
            ["backgroundNormal"] = ("Fondo: normal", "fondo_normal"),
            ["backgroundSelected"] = ("Fondo: elegida", "fondo_elegida"),
            ["backgroundDisabled"] = ("Fondo: desactivada", "fondo_desactivada"),
            ["tintText"] = ("Teñir el texto", "tenir_texto"),
            ["textNormal"] = ("Texto: normal", "texto_normal"),
            ["textSelected"] = ("Texto: elegida", "texto_elegida"),
            ["textDisabled"] = ("Texto: desactivada", "texto_desactivada"),
            ["selectedMarker"] = ("Marcador al elegirla", "marcador"),
            ["selectedScale"] = ("Tamaño al elegirla", "escala"),
            ["moreIndicator"] = ("Indicador «hay más»", "mas"),
            // Interfaz: ajustes
            ["bindings"] = ("Botones y sus teclas", "teclas"),
            ["button"] = ("Botón del juego", "boton"),
            ["keys"] = ("Teclas / mando", "enlaces"),
            ["repeatDelay"] = ("Espera antes de repetir (s)", "espera_repeticion"),
            ["repeatInterval"] = ("Intervalo de repetición (s)", "intervalo_repeticion"),
            ["textSpeed"] = ("Velocidad del texto (letras/s)", "velocidad_texto"),
            ["linesPerPage"] = ("Líneas por caja", "lineas"),
            ["charsPerLine"] = ("Letras por línea", "letras_linea"),
            ["cancelAdvancesText"] = ("Cancelar también avanza el texto", "cancelar_avanza"),
            ["holdToSpeedUp"] = ("Mantener acelera el texto", "mantener_acelera"),
            ["cursorSymbol"] = ("Símbolo del cursor", "simbolo_cursor"),
            ["moreSymbol"] = ("Símbolo «hay más»", "simbolo_mas"),
            ["boxColor"] = ("Color de las cajas", "color_caja"),
            ["borderColor"] = ("Color del borde", "color_borde"),
            ["textColor"] = ("Color del texto", "color_texto"),
            ["highlightColor"] = ("Color de lo elegido", "color_elegido"),
            ["disabledColor"] = ("Color de lo desactivado", "color_desactivado"),
            ["fontSize"] = ("Tamaño de letra", "tamano_letra"),
            ["pauseMenuId"] = ("Menú de pausa (id)", "menu_pausa"),
            ["useInterfaceTextSpeed"] = ("Usar la velocidad de texto de los Ajustes", "vel_ajustes"),
            ["menuId"] = ("Menú (id)", "menu"),
            ["cancelButtons"] = ("Botones de Cancelar", "b_cancelar"),
            ["ignore"] = ("Botones que no visitan las flechas", "ignorar"),
        };

        // Opciones de las listas desplegables (miembros de enums), por su nombre en código.
        private static readonly Dictionary<string, string> Enums = new Dictionary<string, string>
        {
            // Categoría de movimiento
            ["MegaEvolution"] = "Megaevolución",
            ["Physical"] = "Físico", ["Special"] = "Especial", ["Status"] = "Estado",
            // Objetivo
            ["SingleEnemy"] = "Un rival", ["Self"] = "Uno mismo", ["AllEnemies"] = "Todos los rivales",
            ["Ally"] = "Un aliado", ["Everyone"] = "Todos", ["Opponent"] = "El rival", ["Other"] = "Rival",
            // Efectos
            ["InflictStatus"] = "Infligir un estado", ["Drain"] = "Drenar (cura % del daño)",
            ["Recoil"] = "Retroceso (% del daño)", ["HealSelf"] = "Curarse (antiguo)",
            ["ChangeStatStage"] = "Subir o bajar una estadística", ["Flinch"] = "Hacer retroceder",
            ["RecoilMaxHp"] = "Perder % de PS máx.", ["Heal"] = "Curar % de PS máx.",
            ["CureStatus"] = "Quitar un estado", ["SetWeather"] = "Cambiar el clima",
            // Dos turnos / daño especial
            ["None"] = "Ninguno", ["Charge"] = "Carga (golpea el turno siguiente)", ["Recharge"] = "Recarga (pierde el turno siguiente)",
            ["Fixed"] = "Daño fijo", ["UserLevel"] = "Igual al nivel del usuario", ["HalfTargetHp"] = "Mitad de los PS del rival",
            ["OneHitKo"] = "KO directo",
            ["ReturnPhysical"] = "Devolver el daño físico (Contraataque)", ["ReturnSpecial"] = "Devolver el daño especial (Manto Espejo)",
            ["Bide"] = "Aguantar y devolver (Venganza)",
            // Curvas
            ["Fast"] = "Rápida", ["MediumFast"] = "Media", ["MediumSlow"] = "Parabólica", ["Slow"] = "Lenta",
            ["Erratic"] = "Errática", ["Fluctuating"] = "Fluctuante", ["Custom"] = "Tabla propia", ["Expression"] = "Fórmulas por tramos",
            // Condiciones
            ["Less"] = "menos de", ["LessOrEqual"] = "como mucho", ["Equal"] = "exactamente",
            ["GreaterOrEqual"] = "al menos", ["Greater"] = "más de", ["NotEqual"] = "distinto de",
            // Objetos
            ["Medicine"] = "Medicina", ["Revive"] = "Revivir", ["StatusCure"] = "Cura de estado", ["PpRestore"] = "Recuperar PP",
            ["Ball"] = "Bola", ["Evolution"] = "Evolución", ["BattleBoost"] = "Objeto de combate", ["Held"] = "Equipable",
            ["Vitamin"] = "Amistad / vitaminas", ["Key"] = "Objeto clave",
            // Evolución
            ["Level"] = "Por nivel", ["Item"] = "Con un objeto", ["Friendship"] = "Por amistad (al subir de nivel)",
            ["Trade"] = "Por intercambio", ["LevelUp"] = "Al subir de nivel (con condiciones)",
            // Condiciones de evolución
            ["MinLevel"] = "Nivel mínimo", ["MinFriendship"] = "Amistad mínima", ["HoldsItem"] = "Lleva equipado un objeto",
            ["KnowsMove"] = "Sabe un movimiento", ["KnowsMoveOfType"] = "Sabe un movimiento de un tipo", ["TimeOfDay"] = "Momento del día",
            ["AtLocation"] = "Está en un lugar", ["MapWeather"] = "Clima del mapa", ["StatRelation"] = "Ataque frente a Defensa",
            ["PartyHasSpecies"] = "Hay una especie en el equipo", ["PartyHasType"] = "Hay un tipo en el equipo", ["Nature"] = "Naturaleza",
            ["Chance"] = "Según su personalidad (%)", ["GameFlag"] = "Marca de la partida activa",
            ["Day"] = "De día (6-18 h)", ["Night"] = "De noche (18-6 h)", ["Morning"] = "Por la mañana (6-10 h)", ["Evening"] = "Al atardecer (17-20 h)",
            ["AttackHigher"] = "Ataque mayor que Defensa", ["DefenseHigher"] = "Defensa mayor que Ataque", ["AttackEqualsDefense"] = "Ataque igual a Defensa",
            // IA
            ["Easy"] = "Fácil", ["Normal"] = "Normal", ["Hard"] = "Difícil",

            // Efectos nuevos
            ["SetHazard"] = "Poner una trampa", ["ClearHazards"] = "Quitar trampas", ["ForceSwitch"] = "Obligar a cambiar",
            ["SetSideCondition"] = "Poner un efecto de lado", ["ResetStages"] = "Reiniciar etapas", ["CritBoost"] = "Subir el crítico",
            ["Substitute"] = "Crear un sustituto", ["DisableMove"] = "Anular su último movimiento", ["Encore"] = "Obligar a repetir (Otra Vez)",
            ["Rampage"] = "Encadenar turnos (Saña)", ["Rage"] = "Furia (sube al recibir golpes)", ["CallRandomMove"] = "Usar un movimiento al azar",
            ["CallLastMove"] = "Usar el último del rival (Espejo)", ["CopyLastMove"] = "Copiar el último del rival (Mimético)",
            ["Transform"] = "Transformarse en el rival", ["ChangeType"] = "Cambiar de tipo", ["SwitchSelf"] = "Cambiarse tras el golpe",
            ["Teleport"] = "Teletransporte (escapar o cambiarse)",
            // Entrenadores / partida
            ["Random"] = "Al azar (novato)", ["Smart"] = "Listo / inteligente", ["Expert"] = "Experto",
            ["Predictor"] = "Predictor (anticipa tu jugada)", ["Battle"] = "Lo visto en este combate",
            ["Memory"] = "Memoria (recuerda revanchas)", ["Omniscient"] = "Todo (injusto)", ["Basic"] = "Básicos (Restos, bayas, de tipo)",
            ["Competitive"] = "De competición",
            ["Aggressive"] = "El más eficaz según los tipos", ["Never"] = "Nunca", ["Simple"] = "Simple (en cuanto baja del umbral)",
            ["Preset"] = "Equipo prearmado", ["Starter"] = "Desde cero (un inicial)", ["Manual"] = "Equipo escrito aquí",
            ["Wild"] = "Salvaje", ["Trainer"] = "Entrenador", ["Zone"] = "Zona salvaje", ["Legacy"] = "Rival escrito aquí (antiguo)",
            // Interfaz
            ["Close"] = "Cerrar el menú", ["OpenMenu"] = "Abrir otro menú", ["OpenParty"] = "Abrir el equipo", ["OpenBag"] = "Abrir la mochila",
            ["OpenSummary"] = "Resumen del primero", ["OpenPokedex"] = "Pokédex (próximamente)", ["OpenTrainerCard"] = "Ficha de entrenador",
            ["Save"] = "Guardar (próximamente)", ["Options"] = "Opciones", ["ScreenAction"] = "Acción de la pantalla",
            ["TopRight"] = "Arriba a la derecha", ["BottomRight"] = "Abajo a la derecha", ["BottomLeft"] = "Abajo a la izquierda",
            ["TopLeft"] = "Arriba a la izquierda", ["Center"] = "Centro", ["BottomFull"] = "Abajo, a lo ancho",
            ["Up"] = "Arriba", ["Down"] = "Abajo", ["Left"] = "Izquierda", ["Right"] = "Derecha", ["Confirm"] = "Confirmar (A)",
            ["Cancel"] = "Cancelar (B)", ["Menu"] = "Menú (Start)", ["Select"] = "Especial (Select)",
            ["Automatic"] = "Automático (a la opción más cercana)", ["Vertical"] = "Lista vertical", ["Horizontal"] = "Fila horizontal",
            ["Grid"] = "Rejilla (columnas)", ["ChooseOption"] = "Elegir una opción", ["Nothing"] = "Nada",
            ["Selected"] = "Elegida", ["Disabled"] = "Desactivada",
            ["ByAi"] = "Según su IA", ["Classic"] = "Clásico (los 4 últimos que aprende)", ["Balanced"] = "Equilibrado (ataque + cobertura + apoyo)",
            ["Strong"] = "Fuerte (los que más daño hacen: difícil)",
        };

        /// <summary>Etiqueta en español de un campo. Si falta en el diccionario, "separa" el nombre en palabras.</summary>
        public static string Field(string fieldName)
            => fieldName != null && Fields.TryGetValue(fieldName, out var v) ? v.label : Nicify(fieldName);

        /// <summary>¿Hay traducción para este campo? (la auditoría de textos lo usa para avisar de huecos).</summary>
        public static bool HasField(string fieldName) => fieldName != null && Fields.ContainsKey(fieldName);

        /// <summary>Opción de enum en español (si falta, el nombre separado en palabras).</summary>
        public static string Enum(string memberName)
            => memberName != null && Enums.TryGetValue(memberName, out var v) ? v : Nicify(memberName);

        public static bool HasEnum(string memberName) => memberName != null && Enums.ContainsKey(memberName);

        /// <summary>Cabecera corta para Excel (sin espacios). Si falta, el nombre del campo.</summary>
        public static string CsvHeader(string fieldName)
            => fieldName != null && Fields.TryGetValue(fieldName, out var v) ? v.csv : fieldName;

        /// <summary>"residualDamagePercent" → "Residual damage percent" (último recurso si falta traducción).</summary>
        public static string Nicify(string name)
        {
            if (string.IsNullOrEmpty(name)) return name ?? "";
            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                if (i > 0 && char.IsUpper(c) && !char.IsUpper(name[i - 1])) sb.Append(' ');
                sb.Append(i == 0 ? char.ToUpper(c, CultureInfo.InvariantCulture) : char.ToLowerInvariant(c));
            }
            return sb.ToString();
        }
    }
}
